# kubectl create -f persitent-volume-claim.yml
# kubectl get persistentvolumeclaim
# kubectl delete persistentvolumeclaim myclaim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi