# > kubectl create -f pod-definition.yml
# > kubectl get pods
# > kubectl get pods -o wide
# > kubectl delete pods myapp-pod

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx