# kubectl create -f cron-job-definition.yaml
# kubectl get cronjob

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - name: random-error
              image: kodekloud/randomerror
          restartPolicy: Never