# Imperative approach
# > kubectl create configmap \
#   app-config --from-literal=APP_COLOR=blue \
#              --from-literal=APP_MOD=prod
#
# Declarative approach
# > kubectl create -f config-map.yaml
#
# List ConfigMaps
# > kubectl get configmaps
# > kubectl describe configmaps

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod