# Used when a container is up and running but not responding.
# A good use case is when a website can be reached but is not responding
# to user requests

apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp
    image: simple-webapp
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /api/health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 8