# Always create a nodel with labels before creating a pod with node selectors
# > kubectl labels nodes <node-name> <label-key>=<label-value>
# > kubectl labels nodes node-1 size=large
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
  nodeSelector:
    size: Large