# Imperative command
# > kubectl create secret generic <secret-name> --from-literal=<key>=<value>
# > kubectl create secret generic app-secret --from-literal=DB_HOST=mysql
#
# Declarative approach
# > echo '<secret-value>' | base64
# > echo '<secret-value>' | base64 --decode
# > kubectl create -f secret-data.yaml
#
# > kubectl get secrets
# > kubectl describe secrets
# > kubectl get secret app-secret -o yaml

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzd3Jk